_schema: default
glossary_term_name: Unified Configuration
term_description: >-
  A single configuration approach in CloudCannon that consolidates all *Site* settings, build options, and editing configurations into one comprehensive system, simplifying site management and reducing complexity. As of October 2024, CloudCannon uses the Unified Configuration format for all new *Sites*. Sites created before this date can also upgrade to the Unified Configuration format.
documentation_link:
