_schema: default
glossary_term_name: Unified Configuration
term_description: >-
  A single configuration approach in CloudCannon that consolidates all site settings, build options, and editing configurations into one comprehensive system, simplifying site management and reducing complexity.
documentation_link: /developer/articles/what-is-headless-mode/
