_schema: default
glossary_term_name: Initial Site Settings
term_description: >-
  By adding an *Initial Site Settings File* in your *Git Repository*, you can instruct CloudCannon on how to configure your *Site* without completing the *Site* onboarding process.
documentation_link: /documentation/developer-articles/configure-your-initial-site-settings/
