_schema: default
glossary_term_name: Configuration File
term_description: >-
  A Configuration File contains settings and options that control how CloudCannon and your static site generator behave.
documentation_link: /developer/articles/split-your-configuration-file/
