_schema: default
glossary_term_name: Configuration Mode
term_description: >-
  *Configuration Mode* allows you to modify your *Configuration File* from any page in the app, allowing you to see your changes in real time. The *Configuration Mode* switch is on the right side of the *Site Header*.
documentation_link: /developer-articles/what-is-configuration-mode/
