_schema: default
glossary_term_name: Configuration Cascade
term_description: >-
  A hierarchical set of file locations for adding CloudCannon configuration, allowing you to specify configuration options at different levels across a *Site* on CloudCannon. This includes *Site*-wide, *Collection*-specific, *Schema*-specific, *Structure*-specific, and file-specific configuration. Configuration options that can be defined in the configuration cascade include Inputs, Previews, and more.
documentation_link: /developer-articles/using-the-configuration-cascade/
