_schema: default
glossary_term_name: Configuration Files
term_description: >-
  *CloudCannon Configuration Files* store the preferences and settings for your *Site*, allowing you to customize its functionality and appearance. CloudCannon supports cloudcannon.config.json, cloudcannon.config.yaml, or cloudcannon.config.yml file types, and allows you to split your configuration across multiple files.
documentation_link: /developer-articles/what-is-the-cloudcannon-configuration-file/
