_schema: default
glossary_term_name: Org Settings
term_description: >-
  The settings page for a CloudCannon *Organization*, where organization administrators can manage organization-wide settings, including billing, team permissions, integrations, branding, and security policies. You can access this page using the *Organization Settings* link in the *App Sidebar*.  
documentation_link:
