_schema: default
key_name: data_config
key_singular_name: data_config
key_value_type:
  - Object
key_description: >-
  This key defines which file or folder data in your Site is available to
  populate [Select and Multiselect
  inputs](/documentation/articles/select-and-multiselect-inputs/).


  This key has no default.
key_documentation:
  text: defining your data
  url: /documentation/articles/define-your-data/
parent_keys:
subkeys:
