_schema: default
glossary_term_name: Account Settings
term_description: >-
  The *Account Settings* page allows you to manage your profile information, password, multi-factor authentication, and OAuth Providers. You can access the *Account Settings* page by clicking on your *Avatar* in the bottom left of the *App Sidebar*.
documentation_link: 
